DROP TABLE IF EXISTS ZEPTO;

CREATE TABLE ZEPTO
(
SKU_ID SERIAL PRIMARY  KEY,
CATEGORY VARCHAR(120),
PRODUCT_NAME VARCHAR(150) NOT NULL,
PRODUCT_MRP NUMERIC(8,2),
DISCOUNT_PERCENT NUMERIC (5,2),
AVAILABLE_QUANTITY INTEGER,
DISCOUNTED_SELLING_PRICE NUMERIC (8,2),
WEIGHT_IN_GRAMS INTEGER,
OUT_OF_STOCK INTEGER,
QUANTITY INTEGER
);

ALTER TABLE zepto
MODIFY COLUMN OUT_OF_STOCK BOOLEAN;

UPDATE zepto
SET OUT_OF_STOCK = 'TRUE'
WHERE OUT_OF_STOCK = 1;

UPDATE zepto
SET OUT_OF_STOCK = 'FALSE'
WHERE OUT_OF_STOCK = 0;


SELECT * FROM ZEPTO;

-- DATA EXPLORATION

-- 1.] SAMPLE DATA
SELECT * FROM ZEPTO
LIMIT 10;

-- 2.] COUNT OF ROWS
SELECT COUNT(*) FROM ZEPTO;

-- 3.] NULL VALUES
SELECT * FROM zepto
WHERE CATEGORY IS NULL
OR
PRODUCT_NAME IS NULL
OR
PRODUCT_MRP IS NULL
OR
DISCOUNT_PERCENT IS NULL
OR
AVAILABLE_QUANTITY IS NULL
OR
DISCOUNTED_SELLING_PRICE IS NULL
OR
WEIGHT_IN_GRAMS IS NULL
OR
OUT_OF_STOCK IS NULL
OR
QUANTITY IS NULL;

-- 4.] dIFFERENT PRODUCT CATEGORIES
SELECT DISTINCT CATEGORY
FROM zepto
group by CATEGORY;

-- 5.] PRODUCTS IN STOCK V/S. OUT OF STOCK
SELECT OUT_OF_STOCK, count(SKU_ID)
FROM ZEPTO
group by OUT_OF_STOCK;

-- 6.] PRODUCT NAMES PRESENT MULTIPLE TIMES
SELECT PRODUCT_NAME, count(SKU_ID) AS "NUMBER OF SKU'S"
FROM ZEPTO
GROUP BY PRODUCT_NAME
HAVING count(SKU_ID)
ORDER BY count(SKU_ID) DESC;

-- DATA CLEANING
-- 1.] PRODUCTS WITH PRICE = 0
SELECT *
FROM zepto
WHERE PRODUCT_MRP=0 OR DISCOUNTED_SELLING_PRICE = 0 ;

-- 2.] REMOVE PRODUCTS WITH PRICE = 0
DELETE FROM zepto
WHERE PRODUCT_MRP = 0;

-- 3.] CONVERT PAISE TO RUPEES
UPDATE ZEPTO
SET PRODUCT_MRP = PRODUCT_MRP/100.0,
DISCOUNTED_SELLING_PRICE = DISCOUNTED_SELLING_PRICE/100.0;

SELECT SKU_ID,PRODUCT_MRP, DISCOUNTED_SELLING_PRICE
FROM ZEPTO;

 -- **BUISNESS QUESTIONS**
 
 -- Q1.] FIND THE BEST VALUE PRODUCTS BASED ON THE DISCOUNT PERCENTAGE?
 SELECT DISTINCT PRODUCT_NAME,PRODUCT_MRP,DISCOUNT_PERCENT
 FROM ZEPTO
 ORDER BY DISCOUNT_PERCENT DESC
 LIMIT 10;
 
-- Q2.] WHICH ARE THE PRODUCTS WITH HIGH MRP BUT OUT OF STOCK
SELECT PRODUCT_NAME,PRODUCT_MRP,OUT_OF_STOCK
FROM ZEPTO
WHERE OUT_OF_STOCK = TRUE AND PRODUCT_MRP>300
ORDER BY PRODUCT_MRP DESC
LIMIT 10;

-- Q3.] CALCULATE ESTIMATED REVENUE FOR EACH CATEGORY
SELECT SUM(DISCOUNTED_SELLING_PRICE*AVAILABLE_QUANTITY) AS TOTAL_REVENUE, CATEGORY
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE
LIMIT 10; 

-- Q4.] FIND ALL PRODUCTS WHERE MRP IS GREATER THAN RS.500 AND DISCOUNT IS LESS THAN 10%
 SELECT DISTINCT PRODUCT_NAME, PRODUCT_MRP, DISCOUNT_PERCENT
 FROM zepto
 WHERE PRODUCT_MRP>500 AND DISCOUNT_PERCENT<10
 ORDER BY PRODUCT_MRP  DESC, DISCOUNT_PERCENT DESC;
 
-- Q5.] IDENTIFY THE TOP 10 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT PERCENTAGE
SELECT CATEGORY, ROUND(AVG(DISCOUNT_PERCENT),2) AS AVERAGE_DISCOUNT_PERCENTAGE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY AVERAGE_DISCOUNT_PERCENTAGE DESC
LIMIT 10;

-- Q6.] FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100GM AND SORT BY BEST values
SELECT DISTINCT PRODUCT_NAME, WEIGHT_IN_GRAMS, DISCOUNTED_SELLING_PRICE,
ROUND(DISCOUNTED_SELLING_PRICE/WEIGHT_IN_GRAMS,2) AS PRICE_PER_GRAM
FROM ZEPTO
WHERE WEIGHT_IN_GRAMS>=1000
ORDER BY PRICE_PER_GRAM;

-- Q7.] GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW, MEDIUM, BULK
SELECT DISTINCT PRODUCT_NAME, WEIGHT_IN_GRAMS,
CASE WHEN WEIGHT_IN_GRAMS < 1000 THEN 'LOW'
WHEN WEIGHT_IN_GRAMS < 5000 THEN 'MEDIUM'
ELSE 'BULK'
END AS WEIGHT_CATEGORYY
FROM ZEPTO;

-- Q8.] WHAT IS THE TOTAL INVENTORY  WIEGHT PER CATEGORY?  
SELECT CATEGORY, SUM(WEIGHT_IN_GRAMS * AVAILABLE_QUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT;
 